In [22]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [3]:
!wget -O drug200.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv

--2020-05-06 17:52:41--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6027 (5.9K) [text/csv]
Saving to: ‘drug200.csv’

drug200.csv         100%[===================>]   5.89K  --.-KB/s    in 0s      

2020-05-06 17:52:44 (254 MB/s) - ‘drug200.csv’ saved [6027/6027]



In [23]:
df = pd.read_csv("drug200.csv")
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [24]:
df[0:5]

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [25]:
df.size

1200

In [26]:
df.shape

(200, 6)

In [27]:
X = df[['Age','Sex','BP','Cholesterol','Na_to_K']].values
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.113999999999999],
       [28, 'F', 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [28]:
from sklearn import preprocessing
from pandas import get_dummies
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1])
le_bp = preprocessing.LabelEncoder()
le_bp.fit(['LOW','NORMAL','HIGH'])
X[:,2] = le_bp.transform(X[:,2])
le_chol = preprocessing.LabelEncoder()
le_chol.fit(['NORMAL','HIGH'])
X[:,3] = le_chol.transform(X[:,3])

X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [21]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Chol.transform(X[:,3]) 

X[0:5]

ValueError: y contains previously unseen labels: 0

In [29]:
y = df["Drug"]
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

In [32]:
print(X_trainset)
print(y_trainset)

[[26 0 0 1 19.160999999999998]
 [41 0 2 1 22.905]
 [28 0 2 0 19.675]
 [19 0 0 0 13.312999999999999]
 [50 1 2 1 15.79]
 [24 1 2 0 25.785999999999998]
 [72 1 1 0 16.31]
 [74 0 1 0 20.941999999999997]
 [37 0 1 1 12.005999999999998]
 [31 1 0 1 17.069000000000003]
 [22 0 2 0 8.607000000000001]
 [20 0 2 1 9.281]
 [28 0 1 0 13.127]
 [59 0 2 0 13.884]
 [15 1 0 1 17.206]
 [51 0 1 1 23.003]
 [45 1 1 1 10.017000000000001]
 [33 0 1 0 33.486]
 [39 1 0 0 9.664]
 [29 0 0 0 29.45]
 [60 1 2 0 15.171]
 [24 0 0 1 18.457]
 [49 0 2 1 9.381]
 [37 1 1 1 8.968]
 [32 0 0 1 10.292]
 [21 0 0 1 28.631999999999998]
 [23 1 2 0 12.26]
 [40 1 0 0 27.826]
 [38 1 1 0 18.295]
 [47 1 1 1 30.568]
 [22 0 0 1 22.818]
 [47 1 0 0 10.402999999999999]
 [30 0 2 0 10.443]
 [69 1 1 0 15.478]
 [42 0 0 0 21.035999999999998]
 [45 1 1 1 8.37]
 [49 1 0 1 6.269]
 [72 1 1 0 6.769]
 [74 1 1 1 11.939]
 [66 0 2 1 8.107000000000001]
 [46 1 2 1 7.285]
 [68 0 2 1 27.05]
 [58 0 0 0 19.416]
 [19 0 0 1 25.969]
 [20 1 0 1 35.639]
 [69 1 1 1 11.455

In [33]:
print(X_testset.shape)
print(y_testset.shape)

(60, 5)
(60,)


In [34]:
tree = DecisionTreeClassifier(criterion = "entropy", max_depth = 4)
tree

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [35]:
tree.fit(X_trainset,y_trainset)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [36]:
predtree = tree.predict(X_testset)

In [38]:
print (predtree [0:5])
print (y_testset [0:5])

['drugY' 'drugX' 'drugX' 'drugX' 'drugX']
40     drugY
51     drugX
139    drugX
197    drugX
170    drugX
Name: Drug, dtype: object


In [40]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predtree))

DecisionTrees's Accuracy:  0.9833333333333333


In [ ]:
from sklearn.externals.six import StringIO
import pydotplus
import matplotlib.image as mpimg
from sklearn import tree
%matplotlib inline 

In [ ]:
dot_data = StringIO()
filename = "drugtree.png"
featureNames = my_data.columns[0:5]
targetNames = my_data["Drug"].unique().tolist()
out=tree.export_graphviz(drugTree,feature_names=featureNames, out_file=dot_data, class_names= np.unique(y_trainset), filled=True,  special_characters=True,rotate=False)  
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png(filename)
img = mpimg.imread(filename)
plt.figure(figsize=(100, 200))
plt.imshow(img,interpolation='nearest')